name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: PKHeX.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore solution
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

    - name: Test solution
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build
